# Generated by Django 4.0.2 on 2022-04-17 18:04

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0006_alter_menu_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('small_title', models.CharField(blank=True, max_length=200, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('header_image', models.ImageField(upload_to='')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('blog_likes', models.ManyToManyField(blank=True, related_name='liked_post', to=settings.AUTH_USER_MODEL, verbose_name='liked_posts')),
                ('restaurant_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.AddConstraint(
            model_name='blogpost',
            constraint=models.UniqueConstraint(fields=('restaurant_owner', 'title'), name='title unique for author'),
        ),
    ]
