# Generated by Django 4.0.2 on 2022-03-15 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.IntegerField(choices=[(0, 'Liked your restaurant'), (1, 'Followed your restaurant'), (2, 'Commented on your restaurant'), (3, 'Liked your blog post'), (4, 'Posted a new blog post'), (5, 'Has updated their menu')])),
                ('read', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to=settings.AUTH_USER_MODEL, verbose_name='notifications')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_sent', to=settings.AUTH_USER_MODEL, verbose_name='notifications_sent')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
